blog/urls.py
from django.urls import path
from . import views


# Namespace urls to avoid conflict with urls named the same way in
# other app folders
app_name = "blog"

urlpatterns = [
    path("", views.index, name="index"),
    # Path to create new articles by registered users
    path("newarticle", views.newarticle_view, name="newarticle"),
    # The slug path must be below any other paths that use slug as an argument
    # because the slug is the final parth of the url in the browser.
    path("<slug>", views.article_detail, name="article_detail"),
]

blog_app_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# Necesary to import static files
from django.conf.urls.static import static
from django.conf import settings
# Necessary for redirecting the homepage
from blog import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path("blog/", include("blog.urls")),
    path("users/", include("users.urls")),
    # Redirects the homepage to the url http://127.0.0.1:8000/
    path("", views.index, name="index")
]

urlpatterns += staticfiles_urlpatterns()
# Necesary to read media files from the database
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views


# Namespace urls to avoid conflict with urls named the same way in
# other app folders
app_name = "users"


urlpatterns = [
    path("signup/", views.signup_view, name="signup"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
]

blog/models.py
from django.db import models
# Import to use the logged in user as the article author.
from django.contrib.auth.models import User


# Create your models here.
class Articles(models.Model):
    title = models.CharField(max_length=150, unique=True)
    # slug is a newspaper term. It is short label generally used in URLs
    # and contain only letters, numbers, underscores or hyphens.
    slug = models.SlugField()
    body = models.TextField()
    # Field authomatically populated when the user submits the article
    date = models.DateTimeField(auto_now_add=True)
    # Field to add a thumbnail for the blog article
    thumbnail = models.ImageField(default="default.png", blank=True)
    # Field to associate the articles with the user that created it. The user
    # in this case is the logged in User that the system registers.
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    """Method to return only a part of the body and display this snippet
    instead of the whole body of the article"""
    def snippet(self):
        return f"{self.body[:100]}..."

blog/forms.py
from django import forms
from . import models


# Class to create a form with the necessary fields to send to the database
# the information of a new article
class NewArticle(forms.ModelForm):
    class Meta:
        # Define the fields to be present and the model where they are
        # inherit from.
        model = models.Articles
        # Fields to include
        fields = ['title', 'body', 'slug', 'thumbnail']

blog/views.py
from django.contrib.auth import forms
from django.shortcuts import render
from .models import Articles
# Required to access to websites where log in is required
from django.contrib.auth.decorators import login_required
# Import the file where the forms are created
from . import forms


# Create your views here.
def index(request):
    return render(request, "blog/index.html", {
        "Articles": Articles.objects.all().order_by("date")
    })


def article_detail(request, slug):
    article = Articles.objects.get(slug=slug)
    return render(request, "blog/articleContent.html", {
        'article': article
    })


# log in decorator provides the path to send the user that is not logged
# in to the log in page
@login_required(login_url="/users/login/")
def newarticle_view(request):
    # If user reaches via POST
    if request.method == "POST":
        # Creates the form and get the information posted by the user.
        # As the form submits media files, the reques.FILES argument is
        # required to be passed in.
        form = forms.NewArticle(request.POST, request.FILES)
        # If form is valid, save the article
        if form.is_valid():
            # To save create a variable and store de data, but not commit
            # momentarily
            articleToCreate = form.save(commit=False)
            # Now the actual user (request.User) is assigned as the author
            articleToCreate.author = request.user
            # Save the Article
            articleToCreate.save()
            # Return the arguments and display the list of articles
            return render(request, "blog/index.html", {
                "Articles": Articles.objects.all().order_by("date"),
                "message": "Article Succesfully Posted!",
            })

    # If user reaches via get
    else:
        # Create a new instance of the form for the new article
        form = forms.NewArticle()
        # Render the form variable to newarticle.html
    return render(request, "blog/newarticle.html", {
        "form": form
    })

blog/templates/blog/articleContent.html
{% extends 'blog/layout.html' %} 

{% block title %}
    {{ article.title }}
{% endblock %}

{% block main %}
<br />
<h1 class="titlehome">{{ article.title }}</h1>
<div class="articleDetails">
  <div class="article">
    <img class="thumbnail" src="{{ article.thumbnail.url}}" alt="Thumbnail" />
    <p>{{ article.body }}</p>
    <p>{{ article.date }}</p>
    <br>
    <p>Author: {{article.author.username}}</p>
  </div>
</div>
{% endblock %}

blog/templates/blog/index.html
{% extends "blog/layout.html" %}

{% block title %}
    Homepage
{% endblock %}

{% block main %}
    <br>
    <h1 class="titlehome">Blog Homepage</h1>
    <br>
    <!-- If a message is to be displayed, it will be shown here -->
    {% if message %}
        <div class="message"> {{ message }}</div>
    {% endif %}
    <h2 class="ArticleList">List of Articles</h2>
    <div class="articles">
        <!-- Display the list of articles dinamically-->
            {% for article in Articles %}
            <div class="individualArticle">
                <h4><a href="{% url 'blog:article_detail' article.slug %}" title="{{ article.title }}">{{article.title}}</h4></a>
                <p>{{article.snippet}}</p>
                <p>{{article.date}}</p>
                <br>
                <p class="author">Author: {{article.author.username}}</p>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

blog/templates/blog/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title%} {% endblock %}</title>
    <!-- ?{% now 'U' %} used to reset cache and load the styles.css file -->
    <link rel="stylesheet" href="{% static 'blog/styles.css' %}?{% now 'U' %}" type="text/css">
</head>
<body>  
    <!-- Link to homepage located at the main project directory -->
    <a href="{% url 'index'%}" class="linkhomepage">
        <img src="{% static 'blog/django-python-logo.png' %}" alt="Link to Homepage" width="150px" title="Return to Homepage">
    </a>
    <nav>
        <ul>
            <!-- If the user is authenticated, these two links will be displayed -->
            {% if user.is_authenticated %}
                <li class="usersloggedin">
                    <p>Welcome: {{user.username}}</p>
                </li>
                <li class="floatright">
                    <!-- The following form is necesary to execute the action logout_view created in users/views.py -->
                    <form action="{% url 'users:logout' %}" method="post">
                        {% csrf_token %}
                        <input type="submit" value="Log Out" class="logout" title="Log Out">
                    </form>
                </li>
                <li class="floatright">
                    <form action="{% url 'blog:newarticle' %}" method="post">
                        {% csrf_token %}
                        <input type="submit" value="New Article" class="newarticle" title="New Article">
                    </form>
                </li>
            <!-- If the user is not authenticated, these two links will be diplayed -->
            {% else %}
                <li class="floatright" title="Sign Up!">
                    <a href="{% url 'users:signup' %}" class="logsign">Sign Up</a>
                </li>
                <li class="floatright users" title="Sign In!">
                    <a href="{% url 'users:login' %}" class="logsign">Log In</a>
                </li>
            {% endif %}
        </ul>
    </nav>
    {% block main %}
    {% endblock %}
    <!-- Back to top button hidden. It will appears when scrolling down more than 50 -->
    <button onclick="backToTop()" id="backTopBtn" class="backTopBtn"style="display:none;">Back to Top</button>
    <script src="{% static 'blog/script.js' %}"></script>
</body>
</html>

blog/templates/blog/newarticle.html
{% extends 'blog/layout.html' %}

{% block title %}
    New Article
{% endblock %}

{% block main %}
    <br>
    <h1 class="titlehome">Create a New Article</h1>
    <br><br>
    {% if message %}
        <div class="wrong"> {{ message }} </div>
    {% endif %}
    <br>
    <!-- As the a form submits a media file, its mandatory to use enctype="multipart/form-data" to encript that file -->
    <div class="centering">
        <form class="NewArticle" action="{% url 'blog:newarticle' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Create Article">
        </form>
    </div>
{% endblock %}